/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#121222",
        "on-primary-fixed": "#100069",
        "surface-container-low": "#1a1a2b",
        "background": "#0c0c1d",
        "on-background": "#e3e0f8",
        "inverse-surface": "#e3e0f8",
        "surface-container-highest": "#333345",
        "tertiary-fixed": "#ffdcc6",
        "surface-container": "#1e1e2f",
        "surface-bright": "#38374a",
        "on-surface": "#e3e0f8",
        "on-tertiary-container": "#461f00",
        "tertiary": "#ffb785",
        "on-surface-variant": "#c7c4d8",
        "secondary": "#adc6ff",
        "on-secondary-container": "#e6ecff",
        "surface-tint": "#c4c0ff",
        "tertiary-container": "#db761f",
        "on-tertiary": "#502500",
        "secondary-fixed-dim": "#adc6ff",
        "outline": "#918fa1",
        "inverse-primary": "#4f44e2",
        "error-container": "#93000a",
        "secondary-fixed": "#d8e2ff",
        "primary": "#c4c0ff",
        "inverse-on-surface": "#2f2f40",
        "outline-variant": "#464555",
        "on-secondary": "#002e6a",
        "primary-fixed-dim": "#c4c0ff",
        "on-secondary-fixed": "#001a42",
        "surface": "#121222",
        "surface-container-lowest": "#0c0c1d",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#3622ca",
        "on-primary": "#2000a4",
        "tertiary-fixed-dim": "#ffb785",
        "primary-fixed": "#e3dfff",
        "on-tertiary-fixed-variant": "#713700",
        "surface-variant": "#333345",
        "primary-container": "#8781ff",
        "on-secondary-fixed-variant": "#004395",
        "error": "#EF4444", 
        "on-error-container": "#ffdad6",
        "secondary-container": "#0566d9",
        "on-primary-container": "#1b0091",
        "surface-container-high": "#29283a",
        "on-tertiary-fixed": "#301400",
        "accent-purple": "#6C63FF",
        "accent-blue": "#3B82F6",
        "stress-high": "#EF4444",
        "stress-medium": "#F59E0B",
        "stress-low": "#10B981"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "1rem", // rounded-xl should be 16px
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
